[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false
check_program_id_mismatch = true

[programs.localnet]
susu = "2f6CBrNHZp8oyXPFRXfzroGx5pZ7WyLA6dUqFFpYsX2N"

[programs.devnet]
susu = "2f6CBrNHZp8oyXPFRXfzroGx5pZ7WyLA6dUqFFpYsX2N"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
