import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const BANNER = '// DO NOT EDIT — generated by codama\n';
const IDL_PATH = path.join(__dirname, 'programs/susu/idl/susu.json');
const TS_OUT = path.join(__dirname, 'sdk/ts/src/generated');
const RUST_OUT = path.join(__dirname, 'sdk/rust/src/generated');

const FALLBACK_INSTRUCTIONS = [
  'create_group',
  'accept_invite',
  'start_contributions',
  'post_collateral',
  'contribute',
  'claim_payout',
  'top_up_collateral',
  'withdraw_collateral',
  'slash_member',
  'cancel_group',
];

const FALLBACK_ACCOUNTS = ['Group', 'MemberPosition', 'RotationReceipt'];
const FALLBACK_ERRORS = ['Unimplemented'];
const FALLBACK_SEEDS = {
  GROUP_SEED: 'group',
  MEMBER_SEED: 'member',
  VAULT_SEED: 'vault',
  ROTATION_SEED: 'rotation',
};

function toCamelCase(value) {
  return value
    .replace(/^[A-Z]/, (m) => m.toLowerCase())
    .replace(/[_-]([a-zA-Z0-9])/g, (_, ch) => ch.toUpperCase());
}

function toPascalCase(value) {
  const camel = toCamelCase(value);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function toSnakeCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/[-\s]+/g, '_')
    .toLowerCase();
}

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

async function writeGeneratedFile(filePath, body) {
  await ensureDir(path.dirname(filePath));
  await fs.writeFile(filePath, `${BANNER}${body.trimEnd()}\n`, 'utf8');
}

function buildFallbackIdl() {
  return {
    version: '0.1.0',
    name: 'susu',
    instructions: FALLBACK_INSTRUCTIONS.map((name) => ({ name })),
    accounts: FALLBACK_ACCOUNTS.map((name) => ({ name })),
    errors: FALLBACK_ERRORS.map((name, code) => ({ code, name, msg: `${name} (placeholder)` })),
    metadata: {
      story: '1.3-codama-codegen',
      fallbackGenerated: true,
      generatedAt: new Date().toISOString(),
      seeds: FALLBACK_SEEDS,
    },
  };
}

async function loadIdl() {
  try {
    const raw = await fs.readFile(IDL_PATH, 'utf8');
    return JSON.parse(raw);
  } catch {
    return buildFallbackIdl();
  }
}

function normalizeInstructions(idl) {
  const names = Array.isArray(idl.instructions)
    ? idl.instructions
        .map((item) => item?.name)
        .filter((name) => typeof name === 'string' && name.length > 0)
    : [];

  if (names.length === 0) {
    return FALLBACK_INSTRUCTIONS.map((snake) => ({ snake, camel: toCamelCase(snake), pascal: toPascalCase(snake) }));
  }

  return names.map((raw) => {
    const snake = toSnakeCase(raw);
    return {
      snake,
      camel: toCamelCase(snake),
      pascal: toPascalCase(snake),
    };
  });
}

function normalizeAccounts(idl) {
  const names = Array.isArray(idl.accounts)
    ? idl.accounts
        .map((item) => item?.name)
        .filter((name) => typeof name === 'string' && name.length > 0)
    : [];

  const source = names.length > 0 ? names : FALLBACK_ACCOUNTS;
  return source.map((name) => toPascalCase(name));
}

function normalizeErrors(idl) {
  const names = Array.isArray(idl.errors)
    ? idl.errors
        .map((item) => item?.name)
        .filter((name) => typeof name === 'string' && name.length > 0)
    : [];

  const source = names.length > 0 ? names : FALLBACK_ERRORS;
  return source.map((name) => toPascalCase(name));
}

function normalizeSeeds(idl) {
  const metadataSeeds = idl?.metadata?.seeds;
  if (metadataSeeds && typeof metadataSeeds === 'object') {
    const keys = Object.keys(FALLBACK_SEEDS);
    const complete = keys.every((key) => typeof metadataSeeds[key] === 'string' && metadataSeeds[key].length > 0);
    if (complete) {
      return keys.reduce((acc, key) => {
        acc[key] = metadataSeeds[key];
        return acc;
      }, {});
    }
  }
  return { ...FALLBACK_SEEDS };
}

async function writeTsGenerated({ instructions, accounts, errors, seeds }) {
  const instructionExportLines = instructions
    .map((instruction) => `export * from './${instruction.camel}.js';`)
    .join('\n');
  await writeGeneratedFile(
    path.join(TS_OUT, 'instructions/index.ts'),
    `${instructionExportLines}`,
  );

  for (const instruction of instructions) {
    await writeGeneratedFile(
      path.join(TS_OUT, `instructions/${instruction.camel}.ts`),
      `export type ${instruction.pascal}Accounts = Readonly<Record<string, string>>;
export type ${instruction.pascal}Args = Readonly<Record<string, unknown>>;

export function ${instruction.camel}(
  accounts: ${instruction.pascal}Accounts,
  args: ${instruction.pascal}Args = {},
) {
  return {
    instruction: '${instruction.camel}',
    accounts,
    args,
  } as const;
}`,
    );
  }

  const accountExportLines = accounts.map((name) => `export * from './${name}.js';`).join('\n');
  await writeGeneratedFile(path.join(TS_OUT, 'accounts/index.ts'), accountExportLines);

  for (const account of accounts) {
    await writeGeneratedFile(
      path.join(TS_OUT, `accounts/${account}.ts`),
      `export type ${account} = Readonly<{ raw: Uint8Array }>;

export function decode${account}(data: Uint8Array): ${account} {
  return { raw: data };
}`,
    );
  }

  await writeGeneratedFile(
    path.join(TS_OUT, 'errors/SusuError.ts'),
    `export enum SusuError {
${errors.map((name) => `  ${name} = '${name}',`).join('\n')}
}`,
  );
  await writeGeneratedFile(path.join(TS_OUT, 'errors/index.ts'), `export * from './SusuError.js';`);

  await writeGeneratedFile(
    path.join(TS_OUT, 'seeds.ts'),
    `${Object.entries(seeds)
      .map(([key, value]) => {
        return `export const ${key} = '${value}';\nexport const ${key}_BYTES = new TextEncoder().encode(${key});`;
      })
      .join('\n\n')}`,
  );

  await writeGeneratedFile(
    path.join(TS_OUT, 'index.ts'),
    `export * as instructions from './instructions/index.js';
export * as accounts from './accounts/index.js';
export * as errors from './errors/index.js';
export * from './seeds.js';`,
  );
}

async function writeRustGenerated({ instructions, accounts, errors, seeds }) {
  await writeGeneratedFile(
    path.join(RUST_OUT, 'mod.rs'),
    `pub mod accounts;
pub mod errors;
pub mod instructions;
pub mod seeds;`,
  );

  await writeGeneratedFile(
    path.join(RUST_OUT, 'instructions.rs'),
    `#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SusuInstructionKind {
${instructions.map((instruction) => `    ${instruction.pascal},`).join('\n')}
}

${instructions
  .map(
    (instruction) => `pub fn ${instruction.snake}() -> SusuInstructionKind {
    SusuInstructionKind::${instruction.pascal}
}`,
  )
  .join('\n\n')}`,
  );

  await writeGeneratedFile(
    path.join(RUST_OUT, 'accounts.rs'),
    `${accounts
      .map(
        (account) => `#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ${account};`,
      )
      .join('\n\n')}`,
  );

  await writeGeneratedFile(
    path.join(RUST_OUT, 'errors.rs'),
    `#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SusuError {
${errors.map((name) => `    ${name},`).join('\n')}
}`,
  );

  await writeGeneratedFile(
    path.join(RUST_OUT, 'seeds.rs'),
    `${Object.entries(seeds)
      .map(([key, value]) => `pub const ${key}: &[u8] = b"${value}";`)
      .join('\n')}`,
  );
}

async function main() {
  const idl = await loadIdl();
  const instructions = normalizeInstructions(idl);
  const accounts = normalizeAccounts(idl);
  const errors = normalizeErrors(idl);
  const seeds = normalizeSeeds(idl);

  await writeTsGenerated({ instructions, accounts, errors, seeds });
  await writeRustGenerated({ instructions, accounts, errors, seeds });

  const status = idl?.metadata?.fallbackGenerated ? 'fallback-idl-used' : 'idl-loaded';
  console.log(`sdk:codegen completed (${status})`);
}

main().catch((error) => {
  console.error('sdk:codegen failed', error);
  process.exitCode = 1;
});
